# Pandas Essentials: A Comprehensive Guide
This notebook covers everything from basic data structures to advanced grouping and time-series analysis.

## 1. Setup and Series
A **Series** is a one-dimensional labeled array.

In [8]:
import pandas as pd
import numpy as np

# Dealing with Series
s = pd.Series([10, 20, 30], index=['a', 'b', 'c'])
s

a    10
b    20
c    30
dtype: int64

## 2. Creating DataFrames
We can create DataFrames using dictionaries or lists of lists.

In [9]:
# Dictionary Method
d={'name':['james', 'maya', 'tara'], 
   'age':[20, 27, 2000], 
   'salary':[2000, 3000, 4000]}
df1 = pd.DataFrame(d)

df1

    name   age  salary
0  james    20    2000
1   maya    27    3000
2   tara  2000    4000

In [10]:
# List of Lists Method
LL=[['james', 20, 2000], ['maya', 27, 3000], ['tara', 25, 4000]]
df2=pd.DataFrame(LL, columns=['name', 'age', 'salary'])
df2

    name  age  salary
0  james   20    2000
1   maya   27    3000
2   tara   25    4000

In [11]:
df2.columns

Index(['name', 'age', 'salary'], dtype='str')

In [12]:
df2.index

RangeIndex(start=0, stop=3, step=1)

In [13]:
df2.values

array([['james', 20, 2000],
       ['maya', 27, 3000],
       ['tara', 25, 4000]], dtype=object)

In [14]:
df=pd.read_csv(fil_name.csv, sep=',')

NameError: name 'fil_name' is not defined

## 3. Inspection and Preparation
Understanding the metadata and structure of your data.

In [15]:
print("Index:", df1.index)
print("Columns:", df1.columns)
print("Values:\n", df1.values)

df1.info()      # Structure and data types
df1.describe()  # Statistical summary

# Index Manipulation
df_indexed = df1.set_index('name')
df_reset = df_indexed.reset_index()

# Dropping Data
df_no_salary = df1.drop('salary', axis=1) # Drop Column
df_no_row = df1.drop(0, axis=0)           # Drop first row

Index: RangeIndex(start=0, stop=3, step=1)
Columns: Index(['name', 'age', 'salary'], dtype='str')
Values:
 [['james' 20 2000]
 ['maya' 27 3000]
 ['tara' 2000 4000]]
<class 'pandas.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   name    3 non-null      str
 1   age     3 non-null      int64
 2   salary  3 non-null      int64
dtypes: int64(2), str(1)
memory usage: 217.0 bytes

## 4. Selecting Data
Methods for accessing specific rows and columns.

In [ ]:
# Selection via column and row index
print("Single value [col][row]:", df1['name'][1])

# Label-based selection (.loc)
print("Loc selection:\n", df_indexed.loc['maya', 'age'])

# Position-based selection (.iloc)
print("Iloc selection (1st row, 2nd col):", df1.iloc[0, 1])

Single value [col][row]: maya
Loc selection:
 27
Iloc selection (1st row, 2nd col): 20

## 5. Handling Missing Values
Common strategies for cleaning incomplete data.

In [ ]:
df_na = pd.DataFrame({'A': [1, np.nan, 3], 'B': [np.nan, 5, 6]})

print("Is NA Check:\n", df_na.isna())
print("\nFilled (0):\n", df_na.fillna(0))
print("\nInterpolated:\n", df_na.interpolate())
print("\nDropped Rows:\n", df_na.dropna())

Is NA Check:
        A      B
0  False   True
1   True  False
2  False  False

Filled (0):
      A    B
0  1.0  0.0
1  0.0  5.0
2  3.0  6.0

Interpolated:
      A    B
0  1.0  NaN
1  2.0  5.0
2  3.0  6.0

Dropped Rows:
      A    B
2  3.0  6.0

## 6. Analysis: Grouping and Pivoting
Summarizing data for insights.

In [ ]:
# Re-creating a larger sample
df_analysis = pd.DataFrame({
    'Dept': ['IT', 'HR', 'IT', 'HR', 'IT'],
    'Level': ['Junior', 'Senior', 'Senior', 'Junior', 'Senior'],
    'Salary': [2000, 4000, 4500, 2500, 5000],
    'Experience': [1, 5, 6, 2, 8]
})

# Grouping
print("Mean Salary by Dept:\n", df_analysis.groupby('Dept')['Salary'].mean())
print("Count per Dept:\n", df_analysis.groupby('Dept').size())

# Complex Aggregation
agg_custom = df_analysis.groupby('Dept').agg({'Salary': ['min', 'max'], 'Experience': 'mean'})
print("\nCustom Agg:\n", agg_custom)

# Pivot Table
pivot = df_analysis.pivot_table(index='Dept', columns='Level', values='Salary', aggfunc='mean')
print("\nPivot Table:\n", pivot)

Mean Salary by Dept:
 Dept
HR    3250.000000
IT    3833.333333
Name: Salary, dtype: float64
Count per Dept:
 Dept
HR    2
IT    3
dtype: int64

Custom Agg:
      Salary       Experience
        min   max       mean
Dept
HR     2500  4000        3.5
IT     2000  5000        5.0

Pivot Table:
 Level  Junior  Senior
Dept
HR     2500.0  4000.0
IT     2000.0  4750.0

Here are direct links:

- https://leetcode.com/problems/combine-two-tables/
- https://leetcode.com/problems/employees-earning-more-than-their-managers/
- https://leetcode.com/problems/department-highest-salary/
- https://leetcode.com/problems/department-top-three-salaries/
- https://leetcode.com/problems/customers-who-never-order/

- https://www.hackerrank.com/challenges/revising-aggregations-the-average-function/problem
- https://www.hackerrank.com/challenges/revising-aggregations-the-count-function/problem
- https://www.hackerrank.com/challenges/the-pads/problem
- https://www.hackerrank.com/challenges/earnings-of-employees/problem
- https://www.hackerrank.com/challenges/weather-observation-station-13/problem
- https://www.hackerrank.com/challenges/weather-observation-station-14/problem

In [ ]:
salaries = [1000, 2000, 3000, 4000, 5000]
g = map(lambda x: x*2, salaries)
print(next(g))
print(next(g))

2000
4000

In [ ]:
nums = [1,2,3,4,5]
g = list(filter(lambda x: x%2==0, nums))
print(g)

[2, 4]