# **Pandas Essentials**
This notebook covers everything from basic data structures to advanced grouping and time-series analysis.

## 1. Setup and Series
A **Series** is a one-dimensional labeled array.

In [4]:
import pandas as pd
import numpy as np

# Dealing with Series
s = pd.Series([10, 20, 30], index=['a', 444, 'welcome'])
s

a          10
444        20
welcome    30
dtype: int64

In [5]:
s['a']
s[444]
s['welcome']
type(s)
s.dtype

dtype('int64')

## 2. Creating DataFrames
We can create DataFrames using dictionaries or lists of lists.

In [6]:
# Dictionary Method
d={'name':['james', 'maya', 'tara'], 
   'age':[20, 27, 2000], 
   'salary':[2000, 3000, 4000]}
df1 = pd.DataFrame(d)

df1

    name   age  salary
0  james    20    2000
1   maya    27    3000
2   tara  2000    4000

In [26]:
d = {'a': 100, 'b': 200}
print(d.get('c', 300))

300

In [37]:
import pandas as pd

# Create df1 with 'id' values [10, 20]
df1 = pd.DataFrame({
    'id': [10, 20],
    'data_x': ['A', 'B']
})

# Create df2 with 'id' values [20, 30]
df2 = pd.DataFrame({
    'id': [20, 30],
    'data_y': ['C', 'D']
})

# Perform an inner merge on the 'id' column
result = pd.merge(df1, df2, on='id', how='inner')
concat = pd.concat([df1, df2], ignore_index=True, axis=0, join='inner')

print("DataFrame 1:")
print(df1)
print("\nDataFrame 2:")
print(df2)
print("\nMerge Result:")
print(result)
print("\nNumber of rows in result:", len(result))
print("\nConcatenated Result:")
print(concat)

DataFrame 1:
   id data_x
0  10      A
1  20      B

DataFrame 2:
   id data_y
0  20      C
1  30      D

Merge Result:
   id data_x data_y
0  20      B      C

Number of rows in result: 1

Concatenated Result:
   id
0  10
1  20
2  20
3  30

In [7]:
df1.name[1]

'maya'

In [8]:
# List of Lists Method
LL=[['james', 20, 2000], ['maya', 27, 3000], ['tara', 25, 4000]]
df2=pd.DataFrame(LL, columns=['name', 'age', 'salary'])
df2

    name  age  salary
0  james   20    2000
1   maya   27    3000
2   tara   25    4000

In [9]:
df2.columns

Index(['name', 'age', 'salary'], dtype='str')

In [10]:
df2.index

RangeIndex(start=0, stop=3, step=1)

In [11]:
df2.values

array([['james', 20, 2000],
       ['maya', 27, 3000],
       ['tara', 25, 4000]], dtype=object)

In [12]:
# df=pd.read_csv(fil_name.csv, sep=',')
pd.read_csv('noheaderfile.csv', header=None)

   0   1   2   3      4
0  1   2   3   4  hello
1  5   6   7   8  world
2  9  10  11  12    foo

In [13]:
!head ../data/noheaderfile.csv

head: ../data/noheaderfile.csv: No such file or directory

## 3. Inspection and Preparation
Understanding the metadata and structure of your data.

In [14]:
df=pd.read_csv('students.csv')
df

   student  score
0    Alice     85
1      Bob     90
2  Charlie     78

In [15]:
df.columns      # Return the column labels of the DataFrame
df.index        # Return the index (row labels) of the DataFrame
df.values       # Return the underlying NumPy array of the DataFrame
df.head()       # Display the first 5 rows of the DataFrame
df.tail()       # Display the last 5 rows of the DataFrame
df.describe()   # Generate summary statistics (count, mean, std, min, quartiles, max) for numeric columns
df.info()       # Display DataFrame structure, column data types, and non-null counts

<class 'pandas.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 2 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   student  3 non-null      str
 1   score    3 non-null      int64
dtypes: int64(1), str(1)
memory usage: 195.0 bytes

In [16]:
#Index Manipulation
df.set_index('student')  # Set one or more existing columns as the DataFrame index (column name(s) must be specified_
df.reset_index()          # Reset the index to default integer values (old index becomes a column)

   index  student  score
0      0    Alice     85
1      1      Bob     90
2      2  Charlie     78

In [17]:
# Dropping Data
df.drop(1, inplace=True)  # Drop the row with index label 4 and modify the DataFrame in place
# df = df.drop(4)           # Drop the row with index label 4 and assign the result to df
# df.drop(4, axis=0)        # Drop the row with index label 4 (axis=0 refers to rows)
# df.drop('age', axis=1)    # Drop the column named 'age'
# del df['age']             # Delete the column 'age' from the DataFrame
# df['state'] = 'NY'        # Add a new column 'state' with all values set to 'NY'
# when we drop and then reset the old index becomes part of the column unless we drop=True in reset_index() method.

## 4. Handling Missing Values
Common strategies for cleaning incomplete data.

In [18]:
df = pd.read_csv("missingvaluesfile.csv")
df = df.replace(0, np.nan)         # Replace all 0 values in the DataFrame with NaN (missing values)
# df_na.isna()                       # Return a boolean DataFrame indicating where values are NaN
df.isna().sum(axis=1).sum()        # Count the total number of NaN values across all rows
# np.sum(df.isna(), axis=0)          # Count the number of NaN values in each column
# np.sum(df.isna(), axis=1)          # Count the number of NaN values in each row
# np.sum(np.sum(df.isna(), axis=0))  # Count the total number of NaN values in the entire DataFrame
df.isna().sum(axis=0)   # Count the total number of NaN values by columns

Unnamed: 0    0
one           2
two           2
three         2
four          1
dtype: int64

In [19]:
df

  Unnamed: 0       one       two     three      four
0          a -1.250699 -0.573801  0.705961 -1.015682
1          b       NaN -0.217766  0.655179  1.379276
2          c -0.860359 -1.313747  0.676174  1.034417
3          d       NaN       NaN       NaN       NaN
4          e  0.079169  0.029138  0.239183 -0.492039
5          f -1.149060       NaN       NaN -0.160499

In [20]:
# df_na.dropna()                              # Remove rows that contain at least one NaN value
# df.dropna(axis=1, how='all', inplace=True)  # Drop columns where all values are NaN (modify in place)
# df.dropna(axis=1, how='any')                # Drop columns that contain at least one NaN value
# df_na.fillna(0)                             # Replace all NaN values with 0
# df['one'] = df['one'].fillna(df['one'].mean())  # Replace NaN values in column 'one' with its mean
# df_na.interpolate()                         # Fill NaN values using interpolation
# df.interpolate(method='linear')             # Fill NaN values using linear interpolation
# df.interpolate(method='index')              # Fill NaN values using index-based interpolation

## 5. Selecting Data
Methods for accessing specific rows and columns.

In [21]:
df = pd.read_csv("students (1).csv")
df

     id    name  age education        department
0   123    Luai   25        BA  computer science
1   331    Ziad   27       MBA              math
2   441    Taha   30        BA              math
3   221    Suha   26        BA         chemistry
4   336  Sandra   27       MBA  computer science
5   333   Suzan   21        BA         economics
6   234    Alan   36       PhD         economics
7   230    Rian   34       PhD         economics
8   243    Hana   20       MBA         economics
9   154    Mike   29       PhD              math
10  199    Alma   31       MBA         chemistry
11  291  Robert   33       PhD         chemistry

In [22]:
df.set_index('education', inplace=True)

In [23]:
df['col_name']['row_name']      # Access a value by first selecting a column, then a row label (not recommended)
df.loc['row_name', 'col_name']  # Access a value using explicit row and column labels
# df.iloc[row_id, col_id]         # Access a value using integer-based row and column positions
# df[df.age == 25]["department"]

KeyError: 'col_name'

In [ ]:
# df['age']['MBA']
# df[['age']]

In [ ]:
# df.loc['MBA', 'age']
# df.loc['MBA', ['age','name']]
# df.loc[['MBA','BA'], ['age','name']]
# df.loc[:,['department','name']]
# df.loc['MBA', :]
# df.loc[df.age>22,:]
# df.loc[df.age==27,['name','department']]
# df.loc[(df.age>25)&(df.department=='math'),:]
# df.loc[(df.age>25) & (df.department=='math'),['name']]
# df.loc[(df.age>30)|(df.age<25),['name','age']]

In [ ]:
# df.iloc[0,:]
# df.iloc[[0,-1],:]
# df.iloc[[0,-1],0]
# df.iloc[[0,-1],[0,-1]]
# df.iloc[:3,:]
# df.iloc[-4:,:]
# df.iloc[::2,:]
# df.iloc[::-1,:]
# df.iloc[:,-2:]
# Select the first row (all columns)
df.iloc[0,:]

# Select the first and last row (all columns)
df.iloc[[0,-1],:]

# Select the first and last row, first column only
df.iloc[[0,-1],0]

# Select the first and last row, first and last column only
df.iloc[[0,-1],[0,-1]]

# Select the first three rows (all columns)
df.iloc[:3,:]

# Select the last four rows (all columns)
df.iloc[-4:,:]

# Select every other row (all columns)
df.iloc[::2,:]

# Select all rows in reverse order (all columns)
df.iloc[::-1,:]

# Select all rows, last two columns only
df.iloc[:,-2:]

    age        department
0    25  computer science
1    27              math
2    30              math
3    26         chemistry
4    27  computer science
5    21         economics
6    36         economics
7    34         economics
8    20         economics
9    29              math
10   31         chemistry
11   33         chemistry

## 6. Analysis: Grouping and Pivoting
Summarizing data for insights.

In [ ]:
df.reset_index(inplace=True)

In [ ]:
# df.groupby('col_name')          # Group the DataFrame by the values in column 'col_name'
for t in df.groupby('education'): # Iterate over groups created from the 'education' column
    print(t[0])                   # Print the group name (unique value of 'education')

BA
MBA
PhD

In [ ]:
# df.groupby('department')        # Group the DataFrame by the values in the 'department' column
df.groupby('education').size()    # Count the number of rows in each 'education' group

education
BA     4
MBA    4
PhD    4
dtype: int64

In [ ]:
# df[['education','age','id']].groupby('education').mean()              # Compute the mean of 'age' and 'id' for each education group
# df[['education','age','id']].groupby('education').min()               # Compute the minimum of 'age' and 'id' for each education group
# df[['education','age','id']].groupby('education').max()               # Compute the maximum of 'age' and 'id' for each education group
# df[['education','age']].groupby('education').agg(['min','mean','max']) # Compute min, mean, and max of 'age' for each education group

In [ ]:
# for t in df[['education','department','age']].groupby(['department', 'education']):
#     print(t[0])

In [ ]:
df[['education','department','age']].groupby(['department', 'education']).mean()     # Compute the mean of 'age' for each combination of department and education (department is primary group)
df[['education','department','age']].groupby(['education', 'department']).mean()     # Compute the mean of 'age' for each combination of education and department (education is primary group)
df[['education','department','age']].groupby(['education', 'department']).agg(['min','max'])  # Compute min and max of 'age' for each combination of education and department

df[['education','department','age']].groupby(['education', 'department']).agg({'age': ['min', 'max'], "education": "count"})  # Compute min and max of 'age' for each combination of education and department

                           age     education
                           min max     count
education department
BA        chemistry         26  26         1
          computer science  25  25         1
          economics         21  21         1
          math              30  30         1
MBA       chemistry         31  31         1
          computer science  27  27         1
          economics         20  20         1
          math              27  27         1
PhD       chemistry         33  33         1
          economics         34  36         2
          math              29  29         1

In [ ]:
# .filter(lambda x: condition) keeps only the groups where the lambda returns True.
# Keep only groups where the average age is greater than 30
# df.groupby('department').filter(lambda x: x['age'].mean() > 30)

# Keep only groups with more than 2 members
# df.groupby('department').filter(lambda x: len(x) > 2)

### 7. Pivot Table Explanation

A pivot table in Pandas is used to **summarize and aggregate data** in a table format.

- `index` → rows
- `columns` → columns
- `values` → values to aggregate
- `aggfunc` → aggregation function (default is `mean`)

It is especially useful for **grouping data** and **computing statistics** across multiple categories.

In [ ]:
# Basic pivot table: average age per education and department
df.pivot_table(index='education', columns='department', values='age')  

# Pivot table with sum aggregation
df.pivot_table(index='education', columns='department', values='age', aggfunc='sum')  

# Pivot table with multiple aggregation functions
df.pivot_table(index='education', columns='department', values='age', aggfunc=['mean','min','max'])  

# Pivot table including all columns
df.pivot_table(index='education', values=['age','id'], aggfunc='mean')  

# Pivot table with fill value for missing data
df.pivot_table(index='education', columns='department', values='age', fill_value=0)

department  chemistry  computer science  economics  math
education
BA               26.0              25.0       21.0  30.0
MBA              31.0              27.0       20.0  27.0
PhD              33.0               0.0       35.0  29.0

In [ ]:
df.pivot_table(index='education', columns='department', values='age', aggfunc=['mean','min','max'])

                mean                                        min  \
department chemistry computer science economics  math chemistry
education
BA              26.0             25.0      21.0  30.0      26.0
MBA             31.0             27.0      20.0  27.0      31.0
PhD             33.0              NaN      35.0  29.0      33.0

                                                  max                   \
department computer science economics  math chemistry computer science
education
BA                     25.0      21.0  30.0      26.0             25.0
MBA                    27.0      20.0  27.0      31.0             27.0
PhD                     NaN      34.0  29.0      33.0              NaN


department economics  math
education
BA              21.0  30.0
MBA             20.0  27.0
PhD             36.0  29.0

In [ ]:
df.pivot_table(index='education', columns='department', values='age')

department  chemistry  computer science  economics  math
education
BA               26.0              25.0       21.0  30.0
MBA              31.0              27.0       20.0  27.0
PhD              33.0               NaN       35.0  29.0

Here are some **LeetCode** and **HackerRank** problems that are great for practicing **Pandas** and **data manipulation**:

---

### **LeetCode (Pandas Section)**
LeetCode has a dedicated [Database & Pandas section](https://leetcode.com/problemset/database/?difficulty=Easy&difficulty=Medium&tags=pandas) for DataFrame problems.  
Some recommended problems:
- [196. Delete Duplicate Emails](https://leetcode.com/problems/delete-duplicate-emails/)  
- [175. Combine Two Tables](https://leetcode.com/problems/combine-two-tables/)
- [183. Customers Who Never Order](https://leetcode.com/problems/customers-who-never-order/)
- [1873. Calculate Special Bonus](https://leetcode.com/problems/calculate-special-bonus/)
- [1885. Count Student Number in Departments](https://leetcode.com/problems/count-student-number-in-departments/)
- [1795. Rearrange Products Table](https://leetcode.com/problems/rearrange-products-table/)
- [1965. Employees With Missing Information](https://leetcode.com/problems/employees-with-missing-information/)

All of these can be solved using Pandas in the LeetCode Python (Pandas) environment.

---

### **HackerRank**
HackerRank has a [Pandas tutorial track](https://www.hackerrank.com/domains/tutorials/10-days-of-pandas) and [Python (Pandas) challenges](https://www.hackerrank.com/domains/python/py-pandas).

Some good practice problems:
- [10 Days of Pandas](https://www.hackerrank.com/domains/tutorials/10-days-of-pandas) (all problems)
- [Weather Observation Station series (SQL, but can be practiced in Pandas)](https://www.hackerrank.com/domains/sql/weather-observation-station)
- [Data Munging](https://www.hackerrank.com/challenges/data-munging/problem)
- [Pivot Tables](https://www.hackerrank.com/challenges/pivot-table/problem)

---

### **What to Practice**
- Reading CSVs, setting index, handling missing values
- Filtering, grouping, aggregation (`groupby`, `agg`)
- Pivot tables
- Resetting and setting index
- Dropping columns/rows
- DataFrame/Series selection (`loc`, `iloc`)
- Data cleaning (replace, fillna, dropna)

---

**Tip:**  
On LeetCode, filter for "Pandas" in the "Database" section for hands-on DataFrame practice!

To achieve the exact same result as `df.loc['MBA', ['age', 'name']]` without using `.loc`, you have to split the operation into two chained steps: one for the rows, and one for the columns.

Here is the most common equivalent using just standard brackets `[]`:

**`df[df.index == 'MBA'][['age', 'name']]`**

Here is exactly what that does step-by-step:

1. **`df[df.index == 'MBA']`**: This filters the rows. Because "MBA" is in the index of your DataFrame (the bolded column on the far left), you use `df.index == 'MBA'` to grab only those rows.
2. **`[['age', 'name']]`**: This takes the result of the first step and filters it down to only the two columns you want.

You can also flip the order and it will do the exact same thing:
**`df[['age', 'name']][df.index == 'MBA']`**

**Why `.loc` is still better here:**
While the chained bracket method above works perfectly for *viewing* the data, pandas strongly recommends using `.loc` for this specific operation. If you ever try to assign new values using the chained method (e.g., `df[df.index == 'MBA'][['age', 'name']] = 30`), pandas will throw a `SettingWithCopyWarning` because it gets confused about whether you are modifying the original DataFrame or a temporary copy. `.loc` handles this flawlessly in a single step!