## **Pivot Tables**

A pivot table in Pandas is used to **summarize and aggregate data** in a table format.

- `index` → rows
- `columns` → columns
- `values` → values to aggregate
- `aggfunc` → aggregation function (default is `mean`)

It is especially useful for **grouping data** and **computing statistics** across multiple categories.

In [1]:
df = pd.read_csv("students (1).csv")

NameError: name 'pd' is not defined

In [4]:
# Basic pivot table: average age per education and department
df.pivot_table(index='education', columns='department', values='age')  

# Pivot table with sum aggregation
df.pivot_table(index='education', columns='department', values='age', aggfunc='sum')  

# Pivot table with multiple aggregation functions
df.pivot_table(index='education', columns='department', values='age', aggfunc=['mean','min','max'])  

# Pivot table including all columns
df.pivot_table(index='education', values=['age','id'], aggfunc='mean')  

# Pivot table with fill value for missing data
df.pivot_table(index='education', columns='department', values='age', fill_value=0)

department  chemistry  computer science  economics  math
education
BA               26.0              25.0       21.0  30.0
MBA              31.0              27.0       20.0  27.0
PhD              33.0               0.0       35.0  29.0

## **Combining DataFrames**

In [5]:
import numpy as np
import pandas as pd

## `pd.concat()`

`pd.concat()` is a **Pandas function used to combine multiple DataFrames or Series** along a specified axis.

- **`axis=0`** → Stacks data **vertically** (adds rows).
- **`axis=1`** → Combines data **horizontally** (adds columns).
- **`join='outer'`** → Keeps all indexes (union of indexes).
- **`join='inner'`** → Keeps only common indexes (intersection of indexes).

It is commonly used to append datasets or combine related data structures into a single DataFrame.

In [12]:
df1=pd.DataFrame(np.arange(9).reshape(3,3), columns=['a','b','c'], index=['one', 'two', 'three'])
df1

       a  b  c
one    0  1  2
two    3  4  5
three  6  7  8

In [7]:
df2=pd.DataFrame(np.arange(6).reshape(3,2), columns=['d','e'], index=['three', 'two', 'One'])
df2

       d  e
three  0  1
two    2  3
One    4  5

In [ ]:
pd.concat([df1, df2], axis=0)                # Stack rows vertically (default behavior), matching columns by name
pd.concat([df1, df2], axis=1)                # Combine columns side-by-side, aligning rows by index (outer join by default)
pd.concat([df1, df2], axis=1, join='outer')  # Side-by-side with all indexes included (union of indexes, may create NaNs)
pd.concat([df1, df2], axis=1, join='inner')  # Side-by-side with only common indexes kept (intersection of indexes)

In [14]:
pd.concat([df1, df2], axis=0)                # Stack rows vertically (default behavior), matching columns by name

         a    b    c    d    e
one    0.0  1.0  2.0  NaN  NaN
two    3.0  4.0  5.0  NaN  NaN
three  6.0  7.0  8.0  NaN  NaN
three  NaN  NaN  NaN  0.0  1.0
two    NaN  NaN  NaN  2.0  3.0
One    NaN  NaN  NaN  4.0  5.0

In [15]:
pd.concat([df1, df2], axis=1)                # Combine columns side-by-side, aligning rows by index (outer join by default)

         a    b    c    d    e
one    0.0  1.0  2.0  NaN  NaN
two    3.0  4.0  5.0  2.0  3.0
three  6.0  7.0  8.0  0.0  1.0
One    NaN  NaN  NaN  4.0  5.0

## `pd.merge()`

`pd.merge()` is a **Pandas function used to combine DataFrames based on common column(s) or key(s)** (similar to SQL joins).

- **`on='col'`** → Column name used as the join key (must exist in both DataFrames).
- **`left_on` / `right_on`** → Use different column names as join keys.
- **`how='inner'`** → Keeps only matching rows (default).
- **`how='left'`** → Keeps all rows from the left DataFrame.
- **`how='right'`** → Keeps all rows from the right DataFrame.
- **`how='outer'`** → Keeps all rows from both DataFrames.

It is commonly used when combining datasets that share a common identifier (e.g., ID, email, product code).

In [9]:
df3=pd.DataFrame([['a','b','c'], ['d','e','f'],['g','h','i']], columns=['col1', 'col2', 'col3'])
df3

  col1 col2 col3
0    a    b    c
1    d    e    f
2    g    h    i

In [10]:
df4=pd.DataFrame([['x',1,'i'], ['e',2,'f'], ['b',3,'e'],['z',4,'h']], columns=['col2', 'col4', 'col5'])
df4

  col2  col4 col5
0    x     1    i
1    e     2    f
2    b     3    e
3    z     4    h

In [ ]:
pd.merge(df3, df4, how='outer')            # Keep all rows from both DataFrames (union of keys, fills unmatched with NaN)
pd.merge(df3, df4, how='inner')            # Keep only rows with matching keys in both DataFrames (intersection)
pd.merge(df3, df4, on='col2', how='left')  # Keep all rows from df3, match on 'col2', fill unmatched df4 values with NaN
pd.merge(df3, df4, on='col2', how='right') # Keep all rows from df4, match on 'col2', fill unmatched df3 values with NaN
pd.merge(df3, df4, left_on='col2', right_on='col5', how='inner')  # Match df3['col2'] with df4['col5'], keep only matching rows

In [16]:
pd.merge(df3, df4, how='outer')            # Keep all rows from both DataFrames (union of keys, fills unmatched with NaN)

  col1 col2 col3  col4 col5
0    a    b    c   3.0    e
1    d    e    f   2.0    f
2    g    h    i   NaN  NaN
3  NaN    x  NaN   1.0    i
4  NaN    z  NaN   4.0    h

In [17]:
import pandas as pd

# HR table
HR = pd.DataFrame(
    {
        "index": [1, 2, 3, 4],
        "Name": ["Mike", "Sarah", "Tara", "William"],
        "age": [25, 20, 22, 19],
    }
)

# Payroll table
payroll = pd.DataFrame(
    {
        "index": [1, 2, 3, 4],
        "FName": ["Mike", "Tara", "Sarah", "Alma"],
        "Salary": [2000, 3000, 2500, 5000],
    }
)

# Merge (outer join) on HR.Name == payroll.FName
result = pd.merge(HR, payroll, left_on="Name", right_on="FName", how="outer")

print("HR:\n", HR, "\n")
print("Payroll:\n", payroll, "\n")
print("Merged (outer):\n", result)

HR:
    index     Name  age
0      1     Mike   25
1      2    Sarah   20
2      3     Tara   22
3      4  William   19

Payroll:
    index  FName  Salary
0      1   Mike    2000
1      2   Tara    3000
2      3  Sarah    2500
3      4   Alma    5000

Merged (outer):
    index_x     Name   age  index_y  FName  Salary
0      NaN      NaN   NaN      4.0   Alma  5000.0
1      1.0     Mike  25.0      1.0   Mike  2000.0
2      2.0    Sarah  20.0      3.0  Sarah  2500.0
3      3.0     Tara  22.0      2.0   Tara  3000.0
4      4.0  William  19.0      NaN    NaN     NaN