## Exercise

In [4]:
# Using Data in countries.csv

In [26]:
import pandas as pd
df=pd.read_csv('../data/countries.csv', sep=';')
df

,Country,Country (de),Country (local),Country code,Continent,Capital,Population,Area,Coastline,Government form,Currency,Currency code,Dialing prefix,Birthrate,Deathrate,Life expectancy,Url
0,Afghanistan,Afghanistan,Afganistan/Afqanestan,AF,Asia,Kabul,33332025,652230,0,Presidential islamic republic,Afghani,AFN,93,38.3,13.7,51.3,https://www.laenderdaten.info/Asien/Afghanista...
1,Egypt,Ägypten,Misr,EG,Africa,Cairo,94666993,1001450,2450,Presidential republic,Pfund,EGP,20,30.3,4.7,72.7,https://www.laenderdaten.info/Afrika/Aegypten/...
2,Åland Islands,Ålandinseln,Åland,AX,Europe,Mariehamn,29013,1580,0,Autonomous region of Finland,Euro,EUR,358,0.0,0.0,0.0,https://www.laenderdaten.info/Europa/Aland/ind...
3,Albania,Albanien,Shqipëria,AL,Europe,Tirana,3038594,28748,362,parliamentary republic,Lek,ALL,355,13.1,6.7,78.3,https://www.laenderdaten.info/Europa/Albanien/...
4,Algeria,Algerien,Al-Jaza’ir/Algérie,DZ,Africa,Algiers,40263711,2381741,998,Presidential republic,Dinar,DZD,213,23.0,4.3,76.8,https://www.laenderdaten.info/Afrika/Algerien/...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
243,Wallis and Futuna,Wallis und Futuna,Wallis-et-Futuna,WF,Oceania,Mata-Utu,15664,142,129,Parliamentary democracy (territory of France),Franc,XPF,681,13.3,5.2,79.7,https://www.laenderdaten.info/Ozeanien/Wallis-...
244,Christmas Island,Weihnachtsinsel,Christmas Island,CX,Australia,Flying Fish Cove,2205,135,139,(non-self-governing territory of Australia),Dollar,AUD,6724,0.0,0.0,0.0,https://www.laenderdaten.info/Australien/Weihn...
245,Western Sahara,Westsahara,As-Sahrawiya,EH,Africa,El Aaiún,587020,266000,1110,republic,Dirham,MAD,NaN,29.8,8.2,63.0,https://www.laenderdaten.info/Afrika/Westsahar...
246,Central African Republic,Zentralafrikanische Republik,Centrafrique/Bê-Afrîka,CF,Africa,Bangui,5507257,622984,0,Presidential republic,Franc,XAF,236,34.7,13.5,52.3,https://www.laenderdaten.info/Afrika/Zentralaf...
247,Cyprus,Zypern,Kýpros/Kibris,CY,Asia,Nicosia,1205575,9251,648,Presidential democracy,Euro,EUR,357,11.4,6.7,78.7,https://www.laenderdaten.info/Asien/Zypern/ind...

In [27]:
# keep the following columns only
#     ['Country','Continent','Population','Area','Coastline','Currency','Birthrate','Deathrate','Life expectancy']]
df=df[['Country','Continent','Population','Area','Coastline','Currency','Birthrate','Deathrate','Life expectancy']]
df

,Country,Continent,Population,Area,Coastline,Currency,Birthrate,Deathrate,Life expectancy
0,Afghanistan,Asia,33332025,652230,0,Afghani,38.3,13.7,51.3
1,Egypt,Africa,94666993,1001450,2450,Pfund,30.3,4.7,72.7
2,Åland Islands,Europe,29013,1580,0,Euro,0.0,0.0,0.0
3,Albania,Europe,3038594,28748,362,Lek,13.1,6.7,78.3
4,Algeria,Africa,40263711,2381741,998,Dinar,23.0,4.3,76.8
...,...,...,...,...,...,...,...,...,...
243,Wallis and Futuna,Oceania,15664,142,129,Franc,13.3,5.2,79.7
244,Christmas Island,Australia,2205,135,139,Dollar,0.0,0.0,0.0
245,Western Sahara,Africa,587020,266000,1110,Dirham,29.8,8.2,63.0
246,Central African Republic,Africa,5507257,622984,0,Franc,34.7,13.5,52.3
247,Cyprus,Asia,1205575,9251,648,Euro,11.4,6.7,78.7

In [28]:
# change the column names to lowercase
df.columns = df.columns.str.lower()

In [29]:
df.head()

,country,continent,population,area,coastline,currency,birthrate,deathrate,life expectancy
0,Afghanistan,Asia,33332025,652230,0,Afghani,38.3,13.7,51.3
1,Egypt,Africa,94666993,1001450,2450,Pfund,30.3,4.7,72.7
2,Åland Islands,Europe,29013,1580,0,Euro,0.0,0.0,0.0
3,Albania,Europe,3038594,28748,362,Lek,13.1,6.7,78.3
4,Algeria,Africa,40263711,2381741,998,Dinar,23.0,4.3,76.8

In [33]:
# drop columns with missing values
df.isna().sum().sum()
df=df.dropna()
df.head()

,country,continent,population,area,coastline,currency,birthrate,deathrate,life expectancy
0,Afghanistan,Asia,33332025,652230,0,Afghani,38.3,13.7,51.3
1,Egypt,Africa,94666993,1001450,2450,Pfund,30.3,4.7,72.7
2,Åland Islands,Europe,29013,1580,0,Euro,0.0,0.0,0.0
3,Albania,Europe,3038594,28748,362,Lek,13.1,6.7,78.3
4,Algeria,Africa,40263711,2381741,998,Dinar,23.0,4.3,76.8

In [34]:
# limit to countries with populations over 20 million
df=df.loc[df.population>20e6,:]

In [35]:
# reset index to start from zero and count over remaining countries
df.reset_index(drop=True, inplace=True)

In [36]:
df.head()

,country,continent,population,area,coastline,currency,birthrate,deathrate,life expectancy
0,Afghanistan,Asia,33332025,652230,0,Afghani,38.3,13.7,51.3
1,Egypt,Africa,94666993,1001450,2450,Pfund,30.3,4.7,72.7
2,Algeria,Africa,40263711,2381741,998,Dinar,23.0,4.3,76.8
3,Angola,Africa,20172332,1246700,1600,Kwanza,38.6,11.3,56.0
4,Argentina,South America,43886748,2780400,4989,Peso,17.0,7.5,77.1

In [38]:
# add a boolean valued column that is true for countries with coastlines
df['coastal'] = df['coastline']>0
df.head()

,country,continent,population,area,coastline,currency,birthrate,deathrate,life expectancy,coastal
0,Afghanistan,Asia,33332025,652230,0,Afghani,38.3,13.7,51.3,False
1,Egypt,Africa,94666993,1001450,2450,Pfund,30.3,4.7,72.7,True
2,Algeria,Africa,40263711,2381741,998,Dinar,23.0,4.3,76.8,True
3,Angola,Africa,20172332,1246700,1600,Kwanza,38.6,11.3,56.0,True
4,Argentina,South America,43886748,2780400,4989,Peso,17.0,7.5,77.1,True

In [43]:
# Find min and max of the 'life expectancy' for coastal & landlocked countries.
# df.groupby('coastal').agg(['min', 'max'])['life expectancy']
df[['life expectancy','coastal']].groupby('coastal').agg(['min', 'max'])

        life expectancy
                    min   max
coastal
False              51.3  73.8
True               53.3  85.0

In [46]:
# How many coastal and landlocked countries are in each continent? 
df.groupby(['coastal','continent']).size()

coastal  continent
False    Africa            2
         Asia              3
True     Africa           15
         Asia             20
         Australia         1
         Europe            9
         North America     3
         South America     5
dtype: int64

In [47]:
df.groupby(['continent','coastal']).size()

continent      coastal
Africa         False       2
               True       15
Asia           False       3
               True       20
Australia      True        1
Europe         True        9
North America  True        3
South America  True        5
dtype: int64

In [51]:
# Determine the mean deathrate for coastal and landlocked countries in each continent.
df[['continent','coastal','deathrate']].groupby(['coastal','continent']).mean()

                       deathrate
coastal continent
False   Africa          9.150000
        Asia            8.233333
True    Africa          8.293333
        Asia            6.460000
        Australia       7.200000
        Europe         11.100000
        North America   7.333333
        South America   6.140000

In [52]:
df.head()

,country,continent,population,area,coastline,currency,birthrate,deathrate,life expectancy,coastal
0,Afghanistan,Asia,33332025,652230,0,Afghani,38.3,13.7,51.3,False
1,Egypt,Africa,94666993,1001450,2450,Pfund,30.3,4.7,72.7,True
2,Algeria,Africa,40263711,2381741,998,Dinar,23.0,4.3,76.8,True
3,Angola,Africa,20172332,1246700,1600,Kwanza,38.6,11.3,56.0,True
4,Argentina,South America,43886748,2780400,4989,Peso,17.0,7.5,77.1,True

In [53]:
# Create a new column measuring population density. 
df['density']= df['population']/df['area']
df.head()

,country,continent,population,area,coastline,currency,birthrate,deathrate,life expectancy,coastal,density
0,Afghanistan,Asia,33332025,652230,0,Afghani,38.3,13.7,51.3,False,51.104710
1,Egypt,Africa,94666993,1001450,2450,Pfund,30.3,4.7,72.7,True,94.529925
2,Algeria,Africa,40263711,2381741,998,Dinar,23.0,4.3,76.8,True,16.905159
3,Angola,Africa,20172332,1246700,1600,Kwanza,38.6,11.3,56.0,True,16.180582
4,Argentina,South America,43886748,2780400,4989,Peso,17.0,7.5,77.1,True,15.784329

In [54]:
 # Determine the mean population density of all the countries.
df.density.mean()

142.1239784002992

In [55]:
# Create a new column 'dense' that is True for countries with higher than average density and False for lower than average density.
df['dense'] = df['density']>142.1239784002992
df.head()

,country,continent,population,area,coastline,currency,birthrate,deathrate,life expectancy,coastal,density,dense
0,Afghanistan,Asia,33332025,652230,0,Afghani,38.3,13.7,51.3,False,51.104710,False
1,Egypt,Africa,94666993,1001450,2450,Pfund,30.3,4.7,72.7,True,94.529925,False
2,Algeria,Africa,40263711,2381741,998,Dinar,23.0,4.3,76.8,True,16.905159,False
3,Angola,Africa,20172332,1246700,1600,Kwanza,38.6,11.3,56.0,True,16.180582,False
4,Argentina,South America,43886748,2780400,4989,Peso,17.0,7.5,77.1,True,15.784329,False

In [57]:
# For each category of 'dense' compute the mean birthrate and the difference between the maximal birthrate and the minimal birthrate.
def my_diff(x):
    return x.max() - x.min()
df[['birthrate','dense']].groupby('dense').agg(['mean',my_diff])

       birthrate
            mean my_diff
dense
False  21.687805    29.6
True   17.488235    35.6