# **Pandas Essentials**
This notebook covers everything from basic data structures to advanced grouping and time-series analysis.

## 1. Setup and Series
A **Series** is a one-dimensional labeled array.

In [135]:
import pandas as pd
import numpy as np

# Dealing with Series
s = pd.Series([10, 20, 30], index=['a', 444, 'welcome'])  # Create a Pandas Series with custom index labels: 'a', 444, and 'welcome'
s

a          10
444        20
welcome    30
dtype: int64

In [136]:
s['a']        # Access the value in Series `s` using label 'a'
s[444]        # Access the value in Series `s` using label or integer index 444 (depends on the index type)
s['welcome']  # Access the value in Series `s` using label 'welcome'
type(s)       # Return the type of object `s` (usually pandas Series)
s.dtype       # Return the data type of the values stored in the Series

dtype('int64')

## 2. Creating DataFrames
We can create DataFrames using dictionaries or lists of lists.

In [137]:
# Dictionary Method
d = {'name': ['james', 'maya', 'tara'],   # Dictionary key 'name' with a list of employee names
     'age': [20, 27, 2000],               # Dictionary key 'age' with corresponding ages (note: 2000 looks like an outlier)
     'salary': [2000, 3000, 4000]}        # Dictionary key 'salary' with corresponding salaries
df1 = pd.DataFrame(d)                     # Create a DataFrame from dictionary `d`
df1

    name   age  salary
0  james    20    2000
1   maya    27    3000
2   tara  2000    4000

In [138]:
df1.name[1]

'maya'

In [139]:
# List of Lists Method
LL = [['james', 20, 2000], ['maya', 27, 3000], ['tara', 25, 4000]]  # Create a list of lists (each inner list represents a row)
df2 = pd.DataFrame(LL, columns=['name', 'age', 'salary'])           # Create a DataFrame from LL and assign column names
df2

    name  age  salary
0  james   20    2000
1   maya   27    3000
2   tara   25    4000

In [140]:
df = pd.read_csv('students.csv')  # Read a CSV file into a DataFrame using comma as the separator

## 3. Inspection and Preparation
Understanding the metadata and structure of your data.

In [141]:
df=pd.read_csv('students.csv')
df

   student  score
0    Alice     85
1      Bob     90
2  Charlie     78

In [142]:
df.columns

Index(['student', 'score'], dtype='str')

In [143]:
# df.columns      # Return the column labels of the DataFrame
# df.index        # Return the index (row labels) of the DataFrame
# df.values       # Return the underlying NumPy array of the DataFrame
# df.shape
# df.head(2)       # Display the first 5 rows of the DataFrame
# df.tail()       # Display the last 5 rows of the DataFrame
# df.describe()   # Generate summary statistics (count, mean, std, min, quartiles, max) for numeric columns
df.info()       # Display DataFrame structure, column data types, and non-null counts

<class 'pandas.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 2 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   student  3 non-null      str
 1   score    3 non-null      int64
dtypes: int64(1), str(1)
memory usage: 195.0 bytes

In [144]:
df.index

RangeIndex(start=0, stop=3, step=1)

In [145]:
df.values

array([['Alice', 85],
       ['Bob', 90],
       ['Charlie', 78]], dtype=object)

In [146]:
df.shape

(3, 2)

In [147]:
df.head()

   student  score
0    Alice     85
1      Bob     90
2  Charlie     78

In [148]:
# Index Manipulation
df.set_index("student")  # Set one or more existing columns as the DataFrame index (column name(s) must be specified_

         score
student
Alice       85
Bob         90
Charlie     78

In [154]:
import pandas as pd

# Create a DataFrame with index labels including 4
df = pd.DataFrame({
    'name': ['Alice', 'Bob', 'Charlie', 'David', 'Eve'],
    'age': [23, 34, 45, 28, 30]
}, index=[0, 1, 2, 3, 4])

print(df)

# Now you can drop the row with index label 4
df.drop(4, inplace=True)
print("\nAfter dropping index 4:\n", df) # Drop the row with index label 4 and modify the DataFrame in place

      name  age
0    Alice   23
1      Bob   34
2  Charlie   45
3    David   28
4      Eve   30

After dropping index 4:
       name  age
0    Alice   23
1      Bob   34
2  Charlie   45
3    David   28

In [ ]:
df = df.drop(4)           # Drop the row with index label 4 and assign the result to df
df.drop(4, axis=0)        # Drop the row with index label 4 (axis=0 refers to rows)
df.drop('age', axis=1)    # Drop the column named 'age'
del df['age']             # Delete the column 'age' from the DataFrame
df['state'] = 'NY'        # Add a new column 'state' with all values set to 'NY'

KeyError: '[4] not found in axis'

## 4. Handling Missing Values
Common strategies for cleaning incomplete data.

In [ ]:
df=pd.read_csv("missingvaluesfile.csv", index_col=0)
df

FileNotFoundError: [Errno 2] No such file or directory: 'missingvaluesfile.csv'

In [ ]:
# df = df.one.replace(-1, np.nan)    # Replace all 0 values in the DataFrame with NaN (missing values)
# df.isna()                          # Return a boolean DataFrame indicating where values are NaN
# df.isnull()                        # Return a boolean DataFrame indicating where values are null (NaN)
# df.isna().sum()                    # Count the number of NaN values in each column
# df.isna().sum(axis=1)              # Count the number of NaN values in each row
# df.isna().sum().sum()              # Count the total number of NaN values across all rows
# np.sum(df.isna(), axis=0)          # Count the number of NaN values in each column
# np.sum(df.isna(), axis=1)          # Count the number of NaN values in each row
# np.sum(np.sum(df.isna(), axis=0))  # Count the total number of NaN values in the entire DataFrame

In [ ]:
# df.dropna(axis=0, how='any')  # Remove rows that contain at least one NaN value
# df.dropna(axis=1, how='all')  # Drop columns where all values are NaN (modify in place)
# df.dropna(axis=1, how='any')  # Drop columns that contain at least one NaN value

In [ ]:
# df_na.fillna(0)                             # Replace all NaN values with 0
# df['one'] = df['one'].fillna(df['one'].mean())  # Replace NaN values in column 'one' with its mean
# df_na.interpolate()                         # Fill NaN values using interpolation
# df.interpolate(method='linear')             # Fill NaN values using linear interpolation
# df.interpolate(method='index')              # Fill NaN values using index-based interpolation

## 5. Selecting Data
Methods for accessing specific rows and columns.

In [ ]:
df.set_index('education', inplace=True)

KeyError: "None of ['education'] are in the columns"

In [ ]:
# df['col_name']['row_name']      # Access a value by first selecting a column, then a row label (not recommended)
# df.loc['row_name', 'col_name']  # Access a value using explicit row and column labels
# df.iloc[row_id, col_id]         # Access a value using integer-based row and column positions

In [ ]:
# df['age']['MBA']
# df[['age']]

In [ ]:
# df.loc['MBA', 'age']
# df.loc['MBA', ['age','name']]
# df.loc[['MBA','BA'], ['age','name']]
# df.loc[:,['department','name']]
# df.loc['MBA', :]
# df.loc[df.age>22,:]
# df.loc[df.age==27,['name','department']]
# df.loc[(df.age>25)&(df.department=='math'),:]
# df.loc[(df.age>25) & (df.department=='math'),['name']]
# df.loc[(df.age>30)|(df.age<25),['name','age']]

In [ ]:
# df.iloc[0, :]            # Select the first row (all columns) using integer position
# df.iloc[[0, -1], :]      # Select the first and last rows (all columns)
# df.iloc[[0, -1], 0]      # Select the first column values from the first and last rows
# df.iloc[[0, -1],[0, -1]] # Select the first and last columns from the first and last rows
# df.iloc[:3, :]           # Select the first three rows (all columns)
# df.iloc[-4:, :]          # Select the last four rows (all columns)
# df.iloc[::2, :]          # Select every second row (all columns)
# df.iloc[::-1, :]         # Reverse the row order (all columns)
# df.iloc[:, -2:]          # Select the last two columns (all rows)

## 6. Analysis: Grouping and Pivoting
Summarizing data for insights.

In [ ]:
df.reset_index(inplace=True)

In [ ]:
# df.groupby('col_name')          # Group the DataFrame by the values in column 'col_name'
for t in df.groupby('education'): # Iterate over groups created from the 'education' column
    print(t[0])                   # Print the group name (unique value of 'education')

KeyError: 'education'

In [ ]:
# df.groupby('department')        # Group the DataFrame by the values in the 'department' column
df.groupby('education').size()    # Count the number of rows in each 'education' group

KeyError: 'education'

In [ ]:
# df[['education','age','id']].groupby('education').mean()              # Compute the mean of 'age' and 'id' for each education group
# df[['education','age','id']].groupby('education').min()               # Compute the minimum of 'age' and 'id' for each education group
# df[['education','age','id']].groupby('education').max()               # Compute the maximum of 'age' and 'id' for each education group
# df[['education','age']].groupby('education').agg(['min','mean','max']) # Compute min, mean, and max of 'age' for each education group

In [ ]:
# for t in df[['education','department','age']].groupby(['department', 'education']):
#     print(t[0])

In [ ]:
df[['education','department','age']].groupby(['department', 'education']).mean()     # Compute the mean of 'age' for each combination of department and education (department is primary group)
df[['education','department','age']].groupby(['education', 'department']).mean()     # Compute the mean of 'age' for each combination of education and department (education is primary group)
df[['education','department','age']].groupby(['education', 'department']).agg(['min','max'])  # Compute min and max of 'age' for each combination of education and department

KeyError: "None of [Index(['education', 'department', 'age'], dtype='str')] are in the [columns]"

In [ ]:
# .filter(lambda x: condition) keeps only the groups where the lambda returns True.
# Keep only groups where the average age is greater than 30
# df.groupby('department').filter(lambda x: x['age'].mean() > 30)

# Keep only groups with more than 2 members
# df.groupby('department').filter(lambda x: len(x) > 2)

### 7. Pivot Table Explanation

A pivot table in Pandas is used to **summarize and aggregate data** in a table format.

- `index` → rows
- `columns` → columns
- `values` → values to aggregate
- `aggfunc` → aggregation function (default is `mean`)

It is especially useful for **grouping data** and **computing statistics** across multiple categories.

In [ ]:
# Basic pivot table: average age per education and department
df.pivot_table(index='education', columns='department', values='age')  

# Pivot table with sum aggregation
df.pivot_table(index='education', columns='department', values='age', aggfunc='sum')  

# Pivot table with multiple aggregation functions
df.pivot_table(index='education', columns='department', values='age', aggfunc=['mean','min','max'])  

# Pivot table including all columns
df.pivot_table(index='education', values=['age','id'], aggfunc='mean')  

# Pivot table with fill value for missing data
df.pivot_table(index='education', columns='department', values='age', fill_value=0)

KeyError: 'age'