# **Combining DataFrames**

In [1]:
import numpy as np
import pandas as pd

## `pd.concat()`

`pd.concat()` is a **Pandas function used to combine multiple DataFrames or Series** along a specified axis.

- **`axis=0`** → Stacks data **vertically** (adds rows).
- **`axis=1`** → Combines data **horizontally** (adds columns).
- **`join='outer'`** → Keeps all indexes (union of indexes).
- **`join='inner'`** → Keeps only common indexes (intersection of indexes).

It is commonly used to append datasets or combine related data structures into a single DataFrame.

In [2]:
df1=pd.DataFrame(np.arange(9).reshape(3,3), columns=['a','b','c'], index=['one', 'two', 'three'])
df1

       a  b  c
one    0  1  2
two    3  4  5
three  6  7  8

In [50]:
df2=pd.DataFrame(np.arange(6).reshape(-1,2), columns=['d','e'], index=['three', 'two', 'One'])
df2

       d  e
three  0  1
two    2  3
One    4  5

In [51]:
pd.concat([df1, df2], axis=1)

        id  val    d    e
0      1.0    A  NaN  NaN
1      1.0    B  NaN  NaN
three  NaN  NaN  0.0  1.0
two    NaN  NaN  2.0  3.0
One    NaN  NaN  4.0  5.0

In [52]:
pd.concat([df1, df2], axis=0)

        id  val    d    e
0      1.0    A  NaN  NaN
1      1.0    B  NaN  NaN
three  NaN  NaN  0.0  1.0
two    NaN  NaN  2.0  3.0
One    NaN  NaN  4.0  5.0

In [53]:
pd.concat([df1, df2], axis=0)                # Stack rows vertically (default behavior), matching columns by name

        id  val    d    e
0      1.0    A  NaN  NaN
1      1.0    B  NaN  NaN
three  NaN  NaN  0.0  1.0
two    NaN  NaN  2.0  3.0
One    NaN  NaN  4.0  5.0

In [54]:
pd.concat([df1, df2], axis=1)                # Combine columns side-by-side, aligning rows by index (outer join by default)

        id  val    d    e
0      1.0    A  NaN  NaN
1      1.0    B  NaN  NaN
three  NaN  NaN  0.0  1.0
two    NaN  NaN  2.0  3.0
One    NaN  NaN  4.0  5.0

In [55]:
pd.concat([df1, df2], axis=1, join='outer')  # Side-by-side with all indexes included (union of indexes, may create NaNs)

        id  val    d    e
0      1.0    A  NaN  NaN
1      1.0    B  NaN  NaN
three  NaN  NaN  0.0  1.0
two    NaN  NaN  2.0  3.0
One    NaN  NaN  4.0  5.0

In [56]:
pd.concat([df1, df2], axis=1, join='inner')  # Side-by-side with only common indexes kept (intersection of indexes)

Empty DataFrame
Columns: [id, val, d, e]
Index: []

In [57]:
pd.concat([df1, df2], axis=1, join='inner')

Empty DataFrame
Columns: [id, val, d, e]
Index: []

## `pd.merge()`

`pd.merge()` is a **Pandas function used to combine DataFrames based on common column(s) or key(s)** (similar to SQL joins).

- **`on='col'`** → Column name used as the join key (must exist in both DataFrames).
- **`left_on` / `right_on`** → Use different column names as join keys.
- **`how='inner'`** → Keeps only matching rows (default).
- **`how='left'`** → Keeps all rows from the left DataFrame.
- **`how='right'`** → Keeps all rows from the right DataFrame.
- **`how='outer'`** → Keeps all rows from both DataFrames.

It is commonly used when combining datasets that share a common identifier (e.g., ID, email, product code).

In [8]:
df3=pd.DataFrame([['a','b','c'], ['d','e','f'],['g','h','i']], columns=['col1', 'col2', 'col3'])
df3

  col1 col2 col3
0    a    b    c
1    d    e    f
2    g    h    i

In [9]:
df4=pd.DataFrame([['x',1,'i'], ['e',2,'f'], ['b',3,'e'],['z',4,'h']], columns=['col2', 'col4', 'col5'])
df4

  col2  col4 col5
0    x     1    i
1    e     2    f
2    b     3    e
3    z     4    h

In [10]:
# pd.merge(df3, df4, how='outer')            # Keep all rows from both DataFrames (union of keys, fills unmatched with NaN)
# pd.merge(df3, df4, how='inner')            # Keep only rows with matching keys in both DataFrames (intersection)
# pd.merge(df3, df4, on='col2', how='left')  # Keep all rows from df3, match on 'col2', fill unmatched df4 values with NaN
# pd.merge(df3, df4, on='col2', how='right') # Keep all rows from df4, match on 'col2', fill unmatched df3 values with NaN
# pd.merge(df3, df4, left_on='col2', right_on='col5', how='inner')  # Match df3['col2'] with df4['col5'], keep only matching rows

In [11]:
df1 = pd.DataFrame({'key': [1, 2], 'A': ['x', 'y']})
df2 = pd.DataFrame({'key': [2, 3], 'B': ['w', 'z']})
res = pd.merge(df1, df2, on='key', how='outer')

In [12]:
df1

   key  A
0    1  x
1    2  y

In [13]:
df2

   key  B
0    2  w
1    3  z

In [14]:
res

   key    A    B
0    1    x  NaN
1    2    y    w
2    3  NaN    z

In [15]:
res_concat_like_merge = (
    pd.concat(
        [df1.set_index("key"), df2.set_index("key")],
        axis=1,
        join="outer"
    )
    .reset_index()
)
res_concat_like_merge

   key    A    B
0    1    x  NaN
1    2    y    w
2    3  NaN    z

In [16]:
res_concat_like_merge = (
    pd.concat(
        [df1.set_index("key"), df2.set_index("key")],
        axis=0,
        join="outer"
    )
    .reset_index()

)
res_concat_like_merge

   key    A    B
0    1    x  NaN
1    2    y  NaN
2    2  NaN    w
3    3  NaN    z

In [17]:
import pandas as pd
df1 = pd.DataFrame({'id': [1, 2], 'val1': ['A', 'B']})
df2 = pd.DataFrame({'id': [2, 3], 'val2': ['C', 'D']})
res = pd.merge(df1, df2, on='id', how='left')
res

   id val1 val2
0   1    A  NaN
1   2    B    C

In [18]:
import pandas as pd
df = pd.DataFrame({'A': [1, 2, 3]})
df['A'] = df['A'].apply(lambda x: x**2)
print(df['A'].tolist())

[1, 4, 9]

In [19]:
df = pd.DataFrame({"A": [1,2,3]})
df["A"] = df["A"].apply(lambda k: k**2)
print(df)

   A
0  1
1  4
2  9

In [20]:
arr = np.array([1, 2, 4, 4, 5])
print(np.where(arr > 3, 1, 0))

[0 0 1 1 1]

In [21]:
import pandas as pd
import numpy as np
df = pd.DataFrame({'A': [1, np.nan, np.nan],
                   'B': [4, np.nan, 6],
                   'C': [7, np.nan, 9]})
print(df.dropna(how='all').shape)

(2, 3)

In [22]:
import pandas as pd
df1 = pd.DataFrame({'id': [1, 2], 'val1': ['A', 'B']})
df2 = pd.DataFrame({'id': [2, 3], 'val2': ['C', 'D']})
res = pd.merge(df1, df2, on='id', how='outer')
res

   id val1 val2
0   1    A  NaN
1   2    B    C
2   3  NaN    D

In [23]:
import pandas as pd

data = {
    'Dept': ['IT', 'IT', 'HR', 'HR', 'IT', 'HR'],
    'Year': [2023, 2024, 2023, 2024, 2023, 2023],
    'Sales': [100, 150, 200, 250, 50, 50]
}
df = pd.DataFrame(data)

print(df)

  Dept  Year  Sales
0   IT  2023    100
1   IT  2024    150
2   HR  2023    200
3   HR  2024    250
4   IT  2023     50
5   HR  2023     50

In [24]:
import pandas as pd
df1 = pd.DataFrame({'id': [1, 2], 'val1': ['A', 'B']})
df2 = pd.DataFrame({'id': [3, 4], 'val2': ['C', 'D']})
res = pd.merge(df1, df2, on='id', how='inner')
res

Empty DataFrame
Columns: [id, val1, val2]
Index: []

In [25]:
result = df.groupby(['Dept', 'Year'])['Sales'].sum()
print(result)

Dept  Year
HR    2023    250
      2024    250
IT    2023    150
      2024    150
Name: Sales, dtype: int64

In [26]:
import numpy as np
arr = np.arange(8).reshape(-1, 2)


arr

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [27]:
arr = np.arange(6).reshape(2, 3)
arr

array([[0, 1, 2],
       [3, 4, 5]])

In [28]:
print({x: x**2 for x in (1, 2, 3)})

{1: 1, 2: 4, 3: 9}

In [29]:
t = (30, 20)          # Basic tuple with integers
print(t)
t = ("Apple", "Banana")   # Tuple of strings
t = (1, "Hello", 3.14)    # Mixed data types
t = 1, 2, 3               # "Packing": Parentheses are actually optional
t = (5,)                  # Singleton: MUST have a trailing comma for one item
empty = ()                # An empty tuple

(30, 20)

In [30]:
# Goal: Square every number in a list
nums = [1, 2, 3, 4]
squared = list(map(lambda x: x**2, nums)) 
print(squared)  # Output: [1, 4, 9, 16]

# Goal: Convert a list of strings to integers
prices = ["10", "20", "30"]
clean_prices = list(map(int, prices))
print(clean_prices)  # Output: [10, 20, 30]

# Goal: Capitalize names in a list
names = ["ALice", "bob", "charlie"]
caps = list(map(str.upper, names))
# Output: ['ALICE', 'BOB', 'CHARLIE']
print(caps)

list(zip([1, 2], ['a', 'b']))  # Output: [(1, 'a'), (2, 'b')]

[1, 4, 9, 16]
[10, 20, 30]
['ALICE', 'BOB', 'CHARLIE']

[(1, 'a'), (2, 'b')]

In [31]:
import pandas as pd
df1 = pd.DataFrame({'id': [1, 2], 'val1': ['A', 'B']})
df2 = pd.DataFrame({'id': [2, 3, 4], 'val2': ['C', 'D', 'E']})
res = pd.merge(df1, df2, on='id', how='right')
res

   id val1 val2
0   2    B    C
1   3  NaN    D
2   4  NaN    E

In [32]:
import pandas as pd
import numpy as np
df = pd.DataFrame({'A': [1, np.nan, np.nan],
                   'B': [4, np.nan, 6],
                   'C': [7, np.nan, 9]})
print(df.dropna(how='all').shape)
print(df.dropna(how='all'))
df = pd.DataFrame({'A': [1, np.nan, np.nan], #these are columns
                   'B': [4, np.nan, 6],
                   'C': [7, np.nan, 9]})
df

(2, 3)
     A    B    C
0  1.0  4.0  7.0
2  NaN  6.0  9.0

     A    B    C
0  1.0  4.0  7.0
1  NaN  NaN  NaN
2  NaN  6.0  9.0

In [33]:
keys = ['a', 'b']
vals = [1, 2]
print(list(zip(keys,vals)))
print(dict(zip(keys, vals)))

[('a', 1), ('b', 2)]
{'a': 1, 'b': 2}

In [34]:
s1 = {1, 2}
s2 = {1, 2, 3}
print(s1.issubset(s2))

True

In [35]:
import pandas as pd
df1 = pd.DataFrame({'A': [1, 2, 3]})
df2 = pd.DataFrame({'B': [4, 5, 6]})
res = pd.concat([df1, df2], axis=0)
res

     A    B
0  1.0  NaN
1  2.0  NaN
2  3.0  NaN
0  NaN  4.0
1  NaN  5.0
2  NaN  6.0

In [36]:
arr = np.array([[3, 8], [9, 2]])
print(arr.max(axis=1)) # across the columns

[8 9]

In [37]:
# CAREFUL
result = [x * 2 for x in range(5) if x % 2 == 0]
print(result)

[0, 4, 8]

In [38]:
import pandas as pd
data = {'city': ['NYC', 'LA', 'NYC', 'LA', 'NYC'],
        'sales': [100, 200, 150, 300, 50]}
df = pd.DataFrame(data)
print(df.groupby('city')['sales'].sum())

city
LA     500
NYC    300
Name: sales, dtype: int64

In [39]:
cond = np.array([True, False, True])
print(np.where(cond, [1, 2, 3], [4, 5, 6]))

[1 5 3]

In [40]:
d = {'x': [10, 20], 'y': [30, 40], 'z': [50, 60]}
import pandas as pd
df = pd.DataFrame(d)
print(df.shape)

(2, 3)

In [41]:
lst = [5, 10, 15, 20, 25]
lst.extend([10,20])
print(lst.count(10))
print(lst)

2
[5, 10, 15, 20, 25, 10, 20]

In [42]:
lst = [5, 10, 15, 20, 25]
lst.append([10,20])
print(lst.count(10))
print(lst)

1
[5, 10, 15, 20, 25, [10, 20]]

In [43]:
import pandas as pd
df1 = pd.DataFrame({'id': [1, 2, 2], 'val': ['A', 'B', 'C']})
df2 = pd.DataFrame({'id': [2, 3], 'score': [100, 200]})
res = pd.merge(df1, df2, on='id', how='inner')
print(res)
print(df1)
print(df2)

   id val  score
0   2   B    100
1   2   C    100
   id val
0   1   A
1   2   B
2   2   C
   id  score
0   2    100
1   3    200

In [44]:
df1 = pd.DataFrame({'id': [1, 1], 'val': ['A', 'B']})
df2 = pd.DataFrame({'id': [1, 1], 'score': [10, 20]})
res = pd.merge(df1, df2, on='id', how='inner')
print((res.shape))
print(res)

(4, 3)
   id val  score
0   1   A     10
1   1   A     20
2   1   B     10
3   1   B     20