# **Fetching and Reading Data in Shell**

In [ ]:
# View the file
!cat students.txt


Shell can fetch remote data directly.

Common commands:
- `curl` : Sends response to stdout by default
- `wget` : Saves response to a file by default

In [ ]:
# Example using curl
! curl -s https://api.github.com/repos/pandas-dev/pandas -o data.json

In [ ]:
# Example using wget
!wget -q -O data.json https://api.github.com/repos/pandas-dev/pandas


# **Fetching and Reading Data in Python**


## <u>**Text Files**</u>

Python’s built-in `open()` function is used for reading plain text files.
It is best suited for **small to medium-sized unstructured data**.

Key ideas:
- Files are read line-by-line or all at once
- Use `with` to safely manage resources

#### **Writing**

In [ ]:
# Create a sample text file
with open("sample.txt", "w") as f:
    f.write("Alice,85\nBob,90\nCharlie,78")

In [ ]:
f=open("sample.txt",'w')
f.write("Alice,85\nBob,90\nCharlie,78")
f.close()

#### **Reading**

In [ ]:
# Read the entire file
with open("sample.txt", "r") as f:
    content = f.read()

In [ ]:
f=open("sample.txt", "r")
# content = f.read()      # read all of the content as one string 
lines = f.readlines()   # read all lines in a list
f.close()


## <u>**CSV Files**</u>

CSV is one of the most common formats for structured data.
Python provides:
- `csv` module (low-level)
- `pandas.read_csv()` (high-level, recommended)

#### **Creating**

In [ ]:
import pandas as pd

# Create a sample CSV file
# df = pd.DataFrame({
#     "student": ["Alice", "Bob", "Charlie"],
#     "score": [85, 90, 78]
# })
# df
df.to_csv("students.csv", index=False)

#### **Reading**

In [ ]:
# Read CSV using pandas
import pandas as pd
students = pd.read_csv("students.csv")
students

   student  score
0    Alice     85
1      Bob     90
2  Charlie     78

In [ ]:
# For large files, loading everything at once may be inefficient.
# Chunking allows processing data piece by piece.
# Read CSV in chunks
chunks = pd.read_csv("students.csv", chunksize=1)
for chunk in chunks:
    print(chunk)

In [ ]:
import numpy as np
# np.loadtext('sample.txt', dtype=str, delimiter =',')


## <u>**JSON Files**</u>

JSON is commonly used for:
- Configuration files
- API responses

Python reads JSON into dictionaries and lists.

#### **Writing**

In [ ]:
import json

# Create a JSON file
data = {
    "course": "Data Science",
    "students": 30,
    "online": True
}

with open("course.json", "w") as f:
    json.dump(data, f)

#### **Reading**

In [ ]:
# Read JSON file
import json
with open("course.json", "r") as f:
    course_data = json.load(f)

course_data

{'course': 'Data Science', 'students': 30, 'online': True}


## <u>**Web APIs**</u>

APIs return data over HTTP, usually in JSON format.
The `requests` library is the standard tool.

In [ ]:
import requests

response = requests.get("https://api.github.com/repos/pandas-dev/pandas")
data = response.json()
# response.text


## <u>**Databases**</u>

SQLite is a lightweight database stored in a file.
Useful for small applications and teaching SQL basics.

#### **Writing**

In [ ]:

import sqlite3

conn = sqlite3.connect("school.db")
cursor = conn.cursor()

cursor.execute("CREATE TABLE IF NOT EXISTS students (name TEXT, score INTEGER)")
cursor.execute("INSERT INTO students VALUES ('Alice', 85), ('Bob', 90), ('Charlie', 78)")
conn.commit()

#### **Reading**

In [ ]:
# Read data from SQL into pandas
import pandas as pd
query = "SELECT * FROM students"
df_sql = pd.read_sql_query(query, conn)
df_sql

      name  score
0    Alice     85
1      Bob     90
2  Charlie     78


## Final Takeaway

Python provides **multiple layers of data access**:
- Built-in tools for simplicity
- Libraries like Pandas for productivity
- Streaming and chunking for scalability

A good data practitioner chooses the tool based on:
**data size, structure, and source**.